/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'developer' at '27/07/15 23:23' with Gradle 2.5-rc-2
 *
 * @author developer, @date 27/07/15 23:23
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
